### ISSUE TITLE
Downloading Trial version fails on first launch

### ISSUE THREAD

**Issue by piercifani** [ZeeZide/SVGShaper#3]
When launching the trial version of the app for the very first time, the app says I'm past the trial period of the app

I really want to test this with a few SVGs before buying, so how could I fix this?

<img width="372" alt="image" src="https://user-images.githubusercontent.com/869981/189095856-0f036380-b638-47f0-b320-2f1488c57f8b.png">

**Comment by helje5** [comment]
Oops, of course!

**Comment by helje5** [comment]
OK, demo w/ bumped expiration is now up. Thanks for reporting!

https://zeezide.com/en/products/svgshaper/
