### ISSUE TITLE
App crashes when dragging an SVG into an untitled document

### ISSUE THREAD

**Issue by marksands** [ZeeZide/SVGShaper#4]
Cool app! I found a random SVG online to play with it and sadly it froze the app. Here's the image I tried https://upload.wikimedia.org/wikipedia/commons/6/6f/Logo_of_Twitter.svg (though it may have been some alternative found [here](https://commons.wikimedia.org/wiki/File:Logo_of_Twitter.svg)).

I took a spindump, which I can share the whole thing in private if it's helpful, but it looks like perhaps there's some internal deadlock going on:

```
    + 2418 ???  (in SwiftUI)  load address 0x1d11d0000 + 0x120a044  [0x1d23da044]
    +  2418 ???  (in SwiftUI)  load address 0x1d11d0000 + 0x1207b00  [0x1d23d7b00]
    +   2418 _MovableLockLock  (in SwiftUI) + 68  [0x1d11db460]
    +    2418 wait_for_lock  (in SwiftUI) + 144  [0x1d11db518]
    +     2418 _pthread_cond_wait  (in libsystem_pthread.dylib) + 1232  [0x1a8ea8574]
    +      2418 __psynch_cvwait  (in libsystem_kernel.dylib) + 8  [0x1a8e6b710]
    +       2418 Thread_6000710: com.apple.coreanimation.render-server
    +        2418 thread_start  (in libsystem_pthread.dylib) + 8  [0x1a8ea2da0]
    +         2418 _pthread_start  (in libsystem_pthread.dylib) + 148  [0x1a8ea7fa8]
    +          2418 thread_fun(void*)  (in QuartzCore) + 32  [0x1b04ad7b8]
    +           2418 CA::Render::Server::server_thread(void*)  (in QuartzCore) + 564  [0x1b04ad9fc]
    +            2418 mach_msg  (in libsystem_kernel.dylib) + 24  [0x1a8e68290]
    +             2418 mach_msg_overwrite  (in libsystem_kernel.dylib) + 604  [0x1a8e70b78]
    +              2418 mach_msg2_internal  (in libsystem_kernel.dylib) + 80  [0x1a8e7a240]
    +               2418 mach_msg2_trap  (in libsystem_kernel.dylib) + 8  [0x1a8e67f14]
```

**Comment by helje5** [comment]
Seems to work fine for me. When do you get the hang?
<img width="1159" alt="Screenshot 2024-01-08 at 16 41 37" src="https://github.com/ZeeZide/SVGShaper/assets/7712892/acdcb48d-0899-41c7-8824-b7f215287b61">

**Comment by helje5** [comment]
Generated code also works for me.
<img width="1346" alt="Screenshot 2024-01-08 at 16 43 12" src="https://github.com/ZeeZide/SVGShaper/assets/7712892/dc823df9-fb24-4406-a8a5-226db0b604b9">

**Comment by helje5** [comment]
Interesting, the `DropDelegate` runs on a different thread. It crashes in the drop handler on:
> Thread 3 Queue : com.apple.Foundation.NSItemProvider-callback-queue (serial)

Fixed.
